services:
  mongo:
    image: mongo
    restart: always
    container_name: device-service-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

    # This container was included to serve as the MongoDB for the integration tests
    # mongo-test:
    # image: mongo
    # restart: always
    # container_name: device-service-mongo-test
    # ports:
    #   - "27018:27018"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: testuser
    #   MONGO_INITDB_ROOT_PASSWORD: testpassword
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: meuser
      ME_CONFIG_BASICAUTH_PASSWORD: mepassword
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local